#! /usr/bin/env python

from nutils import *


@log.title
def makeplots( domain, geom, stress ):

  points, colors = domain.elem_eval( [ geom, stress[0,1] ], ischeme='bezier3', separate=True )
  with plot.PyPlot( 'stress', ndigits=0 ) as plt:
    plt.mesh( points, colors, triangulate='bezier' )
    plt.colorbar()
    plt.axis( 'equal' )
    plt.xlim( 0, 1.5 )


def main( nelems=8, stress=library.Hooke(lmbda=1,mu=1), degree=2, plots=True ):

  verts = numpy.linspace( 0, 1, nelems+1 )
  domain, geom = mesh.rectilinear( [verts,verts] )
  dspace = domain.splinefunc( degree=degree ).vector( 2 )
  elasticity = function.outer( dspace.grad(geom), stress(dspace,geom) ).sum([2,3])
  matrix = domain.integrate( elasticity, geometry=geom, ischeme='gauss2' )
  nfval = ( dspace * geom.normal() ).sum()

  cons = domain.boundary['left'].project( 0, geometry=geom, onto=dspace, ischeme='gauss2' ) \
       | domain.boundary['right'].project( .5, geometry=geom, onto=nfval, ischeme='gauss2' )
  lhs = matrix.solve( constrain=cons, tol=1e-10, symmetric=True )
  disp = dspace.dot( lhs )

  if plots:
    makeplots( domain, geom+disp, stress(disp,geom) )

  return lhs, cons


def unittest():

  retvals = main( nelems=4, degree=1, plots=False )
  assert debug.checkdata( retvals, '''
    eNqlkMsKAyEMRX9HIUKePj6ni27n/5d11MwgFEpbJBxyc8AQgqBAFiEEBH8kkp+p56Q6Kbr1a84mPKhi
    g9Jo69dcii1Sm0Tc+zk3nPkn3pvmqj0x4FLqySSmfQWqkK7InSpIJ5XZxsAMebpX5E7NpQ1XeTCp5LZc
    j9ypBWW6MphaK66uxJV+5nv343H8XN9f6p/f3lWE+AJ3U40B''' )

  retvals = main( nelems=4, degree=2, plots=False )
  assert debug.checkdata( retvals, '''
    eNq1kkEOhDAIRa+jSUmgFNoeZxZuvf9yKhRHF7OYTIxp3hd+KVQpLSWRrGlZMH2eRrVvIEkQq5E73zjj
    4aOeywajUjveB6vIjRGfPiZGJzlR9caIT1/hypPZKXpnxN03+sNfeJ1dOtpMuWq2GYVGTU1wishAWGun
    dlC5FLuOWskMp4gMhLUpZd+iaKcxueEUkYGwNlErpsrGTKy+JURkIKxN2RsrzZizzFNCRAbCOn6F623s
    r/3R9c+Xerq3b2tN6xs8dM45''' )


util.run( main, unittest )
