#! /usr/bin/env python

from nutils import *


@log.title
def makeplots( domain, geom, sol, index ):

  points, colors = domain.elem_eval( [ geom, sol ], ischeme='bezier4', separate=True )
  with plot.PyPlot( 'solution', index=index ) as plt:
    plt.mesh( points, colors, triangulate='bezier' )
    plt.colorbar()
    plt.xlim( 0, .5*numpy.pi )
    plt.ylim( 0, .5*numpy.pi )


def main( nelems=None, degree=1, plots=True ):

  if nelems:
    verts = numpy.linspace( 0, .5*numpy.pi, nelems+1 )
    domain, geom = mesh.rectilinear( [verts,verts] )
  else:
    domain, geom = mesh.demo( xmax=.5*numpy.pi, ymax=.5*numpy.pi )
    if degree != 1:
      log.warning( 'setting degree=%d for triangular mesh' % degree )
      degree = 1

  x, y = geom
  exact = function.sin(x) * function.exp(y)
  flux = numpy.exp(.5*numpy.pi) * function.sin(x)
  dirichlet = function.sin(x)

  funcsp = domain.splinefunc( degree=degree )
  laplace = function.outer( funcsp.grad(geom) ).sum()
  matrix = domain.integrate( laplace, geometry=geom, ischeme='gauss4', title='matrix' )
  rhs = domain.boundary['top'].integrate( funcsp * flux, geometry=geom, ischeme='gauss6', title='rhs' )
  cons = domain.boundary['left,bottom'].project( dirichlet, ischeme='gauss6', geometry=geom, onto=funcsp, title='left,bottom edge' )
  lhs = matrix.solve( rhs, constrain=cons, tol=1e-8, symmetric=True )
  sol = funcsp.dot(lhs)

  if plots:
    makeplots( domain.refined, geom, sol, nelems )

  error = sol - exact
  err = numpy.sqrt( domain.integrate( [ error**2, ( error.grad(geom)**2 ).sum() ], geometry=geom, ischeme='gauss6', title='computing error' ) )
  log.user( 'errors: l2=%f, h1=%f' % tuple(err) )

  return err, rhs, cons, lhs


def conv( degree=1, nrefine=4 ):

  l2err = []
  h1err = []

  __log__ = log.range( 'refine', nrefine )
  for irefine in __log__:
    err, rhs, cons, lhs = main( nelems=2**irefine, degree=degree )
    l2err.append( err[0] )
    h1err.append( err[1] )

  h = (.25*numpy.pi) * .5**numpy.arange(nrefine)

  with plot.PyPlot( 'convergence' ) as plt:
    plt.subplot( 211 )
    plt.loglog( h, l2err, 'k*--' )
    plt.slope_triangle( h, l2err )
    plt.ylabel( 'L2 error' )
    plt.grid( True )
    plt.subplot( 212 )
    plt.loglog( h, h1err, 'k*--' )
    plt.slope_triangle( h, h1err )
    plt.ylabel( 'H1 error' )
    plt.grid( True )


def unittest():

  retvals = main( degree=1, plots=False )
  assert debug.CmpData( retvals ) == '''
    eNqtkkuKAzEMRK/TYdxCf8nHmUVvc//lKGobsstiYjA8hKwql63jOBzU3K8TeSSgYxTSeIyDQNT4+kEc
    DCgkjQQUIqvq6LPbEbBWV7+KJeHJ10lRwo6ZC8XJGv8vUTd9/j7H3mcN51mSqC91S22sMoa/WIaAiXKj
    gbF6R5Bg0eeo/KHgndz76E+7nCiE+O1LAZl8pVAvRI1ftkcQxnNHrWYLp8pGVaHVyxY3OiTlPddAI7Bx
    QjBtCQmN/XcsY00wCV6pP/4AfMCL6w=='''

  retvals = main( nelems=4, degree=1, plots=False )
  assert debug.CmpData( retvals ) == '''
    eNqtkctqAzEMRX9nhjpC78fndJFt/n9Zj8cOJATagRoMx5aurStp2zYGLbT7DbkphKJ0pLa3DQH7un8h
    tl+RgNlrKK/IAkg8LssIhDL+lvsiCxa8LCsQVl9dMSix46TtRmBFOFiBU7SjHdfMkoMdiIo6ehPI0NPr
    4/vxsnsbnPNjqH9uiR9DBEhco8T30D/VaeCBp/MEiaGjY9bKq6OplmuUy0MvTCNmgmnwQAYuPcsVUOrv
    zuYuf32qnjVzkckmVqUOVFBzmu8+vRNoUsxcyqT5BastWbLIwL3tPy6spXk='''

  retvals = main( nelems=4, degree=2, plots=False )
  assert debug.CmpData( retvals ) == '''
    eNq1kk2OwzAIha+TaBzEP+Y4s+i291+OY7tpq5ks2moiRXoS8Bl4aFkWAk2Xy4ZSGJSDmuSylgUB23f5
    QiyvSAcylA55kyDgpNkI9C6BADn15bInginGZwRKtk8IDqzV+h6aHRtDCu2L1cYWSe5yMyCs0bTt/mFi
    lxuBq1DXARaxc7wVZqJ25PX7+us3cBc5DVfQiPNwNnjF0zDdJ/sr/A8jMkjIkAJGPlo3YJxTBAThuLQE
    87CZcGzBIRyjy7391tuwVitnl9xctjplsA7DHxbVyojqrSyrz1ymeaACXH1IBYwYR/ewy/2QRCch9iYH
    wWnmCtTW5SRUzFvu0ylK3Al5EKochDgIhOOJtaw/1jjpSg=='''


util.run( main, conv, unittest )
