#! /usr/bin/env python

from nutils import *


@parallel.fork
def makeplots( domain, coords, velo, pres, index ):

  log.context( 'figures' )

  funcsp = domain.splinefunc( degree=3 )
  grad = funcsp.grad( coords )
  laplace = function.outer( grad ).sum()
  vort = velo.grad(coords)[1,0] - velo.grad(coords)[0,1]
  matrix, rhs = domain.integrate( [ laplace, vort * funcsp ], coords=coords, ischeme='gauss9' )
  cons = domain.boundary.project( 0, onto=funcsp, coords=coords, ischeme='gauss9' )
  lhs = matrix.solve( rhs, constrain=cons )
  streamfunc = funcsp.dot( lhs )

  xy, uv = domain.elem_eval( [ coords, velo ], ischeme='uniform1', title='flow field', separate=False )
  points, stream, velo, pres, div = domain.elem_eval( [ coords, streamfunc, function.norm2(velo), pres, velo.div(coords) ], ischeme='bezier5', separate=True )

  period = .04
  with plot.PyPlot( 'stream', index=index, ndigits=4 ) as plt:
    from matplotlib import cm
    plt.mesh( points, stream%period, edgecolors='none', triangulate='bezier', cmap=cm.hsv )
    plt.clim( 0, period )
    plt.colorbar()
    plt.xlim( 0, 1 )
    plt.ylim( 0, 1 )

  with plot.PyPlot( 'velo', index=index, ndigits=4 ) as plt:
    plt.mesh( points, velo, edgecolors='none', triangulate='bezier' )
    plt.clim( 0, .9 )
    plt.colorbar()
    plt.quiver( xy[:,0], xy[:,1], uv[:,0], uv[:,1] )
    plt.xlim( 0, 1 )
    plt.ylim( 0, 1 )

  with plot.PyPlot( 'pres', index=index, ndigits=4 ) as plt:
    plt.mesh( points, pres, edgecolors='none', triangulate='bezier' )
    plt.colorbar()
    plt.xlim( 0, 1 )
    plt.ylim( 0, 1 )

  with plot.PyPlot( 'div', index=index, ndigits=4 ) as plt:
    plt.mesh( points, div, edgecolors='none', triangulate='bezier' )
    plt.colorbar()
    plt.xlim( 0, 1 )
    plt.ylim( 0, 1 )


@util.withrepr
def Gauss( center, width, height ):
  return lambda x: height * function.exp( -((x-center)/width)**2 )


def main( nelems=16, reynolds=2e3, bump=Gauss(.75,.25,.25), strong=False, tol=1e-8, timestep=0 ):

  domain, coords = mesh.rectilinear( [(0,1,nelems+1)]*2 )
  #vspace = function.vectorize([ domain.splinefunc( degree=(3,2) ), domain.splinefunc( degree=(2,3) ) ])
  vx, vy = function.chain([
    domain.splinefunc( degree=(3,2), removedofs=[[0,-1],None] ),
    domain.splinefunc( degree=(2,3), removedofs=[None,[0,-1]] )
  ])
  vspace = function.stack( [ vx, vy ], axis=1 )
  pspace = domain.splinefunc( degree=2 )

  if bump:
    x, y = coords
    coords = domain.projection( [ x, bump(x) * (1-y) + y ],
                onto=domain.splinefunc( degree=3 ).vector( 2 ), coords=coords, ischeme='gauss9' )
    # piola
    J = function.localgradient( coords, domain.ndims )
    detJ = function.determinant( J )
    vspace = ( vspace[...,_,:] * J ).sum() / detJ
    pspace = pspace / detJ

  vspace, pspace, lspace = function.chain([ vspace, pspace, [1.] ])

  stress = 2 * vspace.symgrad(coords) - pspace[:,_,_] * function.eye( domain.ndims )

  A = function.outer( vspace.grad(coords), stress ).sum([2,3])
  A += function.outer( pspace, vspace.div(coords) )
  A += function.outer( lspace, pspace )
  A += function.outer( pspace, lspace )

  stokesmat = domain.integrate( A, coords=coords, ischeme='gauss9', title='stokes matrix' )

  if strong:
    stokesrhs = 0
    cons = domain.boundary['top'].project( 1, coords=coords, onto=vspace[:,0], title='top boundary' ) \
         | domain.boundary.project( 0, coords=coords, onto=vspace, title='other boundary' )
  else:
    ALPHA = .01 * nelems * reynolds
    Utop = [1,0]
    weakterm = ALPHA * vspace - 2 * vspace.nsymgrad(coords)
    stokesmat += domain.boundary.integrate( function.outer( weakterm, vspace ).sum(), coords=coords, ischeme='gauss9', title='weak bc stokes matrix' )
    stokesrhs = domain.boundary['top'].integrate( ( weakterm * Utop ).sum(), coords=coords, ischeme='gauss9', title='weak bc rhs' )
    cons = None

  if timestep:
    inertia = (1./timestep) * function.outer( vspace ).sum()
    inertmat = domain.integrate( inertia, ischeme='gauss9', coords=coords, title='adding inertia' )
    stokesmat += inertmat

  lhs = stokesmat.solve( stokesrhs, constrain=cons, tol=1e-10, precon='spilu' )

  for iiter in util.iterate():
    makeplots( domain, coords, vspace.dot(lhs), pspace.dot(lhs), iiter )
    ugradu = ( vspace.grad(coords) * vspace.dot(lhs) ).sum()
    convection = reynolds * function.outer( vspace, ugradu ).sum()
    matrix = stokesmat + domain.integrate( convection, ischeme='gauss9', coords=coords, title='navstokes matrix' )
    if timestep:
      rhs = stokesrhs + inertmat.matvec( lhs )
    else:
      rhs = stokesrhs
      res = matrix.res( lhs, rhs, constrain=cons )
      log.info( 'residual:', res )
      if res < tol:
        break
    lhs = matrix.solve( rhs, constrain=cons, tol=1e-10 )#, precon='spilu' )


#   lhs = stokesmat.solve( rhs, constrain=cons, tol=1e-10 )
#   stokesmat += domain.integrate( (2./timestep) * function.outer( vspace ).sum(), ischeme='gauss9', coords=coords, title='adding inertia' )
#   for iiter in util.iterate( 'timestep' ):
#     velo = vspace.dot( lhs )
#     pres = pspace.dot( lhs )
#     makeplots( domain, coords, velo, pres, iiter )
#     integ = (2./timestep) * ( vspace * velo ).sum()
#     integ -= convec.dot(lhs,axis=2).dot(lhs,axis=1)
#     integ -= ( stress.dot(lhs) * vspace.grad(coords) ).sum([-2,-1])
#     dmatrix, rhs = domain.integrate( [ convec.dot(lhs,axis=2), integ ], ischeme='gauss9', coords=coords, title='navstokes matrix' )
#     if not strong:
#       rhs += domain.boundary['top'].integrate( ( weakterm * ( Utop - velo ) ).sum(), coords=coords, ischeme='gauss9', title='weak bc rhs' )
#       rhs += domain.boundary['left,right,bottom'].integrate( ( weakterm * -velo ).sum(), coords=coords, ischeme='gauss9', title='weak bc rhs' )
#     matrix = stokesmat + dmatrix
#     for iiter in util.iterate( 'picard' ):
#       lhs = matrix.solve( rhs, constrain=cons, tol=1e-10 )
#       matrix = stokesmat + domain.integrate( convec.dot(lhs,axis=2), ischeme='gauss9', coords=coords, title='navstokes matrix' )
#       res = matrix.res( lhs, rhs, constrain=cons )
#       log.info( 'residual:', res )
#       if res < tol:
#         break


util.run( main )
